name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          # extended: true

      - name: Build
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
         # personal_token: ${{ secrets.GITHUB_TOKEN  }}
          deploy_key : ${{ secrets.GIT_TOKEN }} 
          external_repository : guzzhao.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
